#!/usr/bin/env bash
set -euo pipefail

# ─── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'
BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${BLUE}ℹ${RESET}  $*"; }
success() { echo -e "${GREEN}✓${RESET}  $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET}  $*"; }
error()   { echo -e "${RED}✗${RESET}  $*" >&2; }
header()  { echo -e "\n${BOLD}$*${RESET}"; }

# ─── Script directory ─────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

COMPOSE_FILE="deploy/docker-compose.yml"

# ─── Usage ────────────────────────────────────────────────────────────────────
usage() {
  cat <<EOF
${BOLD}Digital Twin Earth — Local Runner${RESET}

Usage: ./run.sh [mode] [command]

Modes (optional):
  mock      Force all feeds to mock/simulated data (no internet required)

Commands:
  up        Build images and start all services (default)
  down      Stop and remove all containers
  restart   Stop then start
  logs      Follow logs from all services
  status    Show container status
  build     Build Docker images only (no start)
  clean     Stop containers and remove volumes (destructive!)
  help      Show this help

Examples:
  ./run.sh up                     Start with default (mock) feeds
  ./run.sh mock up                Start with mock data, explicit
  ./run.sh down                   Stop everything

  MOCK_FLIGHTS_COUNT=20000 \\
  MOCK_SHIPS_COUNT=10000  \\
  ./run.sh mock up                Zing stress-test load

  INGESTION_FEED_FLIGHT=opensky \\
  INGESTION_FEED_SHIP=aisstream  \\
  AISSTREAM_API_KEY=your-key     \\
  ./run.sh up                     Real ADS-B + AIS data

Environment variables:
  MOCK_SEED              Random seed for mock data (default: 42)
  MOCK_FLIGHTS_COUNT     Mock aircraft count (default: 500)
  MOCK_SHIPS_COUNT       Mock vessel count (default: 200)
  MOCK_SATELLITES_COUNT  Mock satellite count (default: 100)
  AISSTREAM_API_KEY      AISStream.io key (required for real ships)
  OPENSKY_USERNAME       OpenSky username (increases rate limit)
  OPENSKY_PASSWORD       OpenSky password
  GATEWAY_API_KEY        Gateway API key (default: dev-key)

EOF
}

# ─── Prerequisites check ──────────────────────────────────────────────────────
check_prereqs() {
  header "Checking prerequisites..."

  local ok=true

  if ! command -v docker &>/dev/null; then
    error "Docker not found. Install Docker Desktop: https://www.docker.com/products/docker-desktop/"
    ok=false
  else
    success "Docker found: $(docker --version | head -1)"
  fi

  if ! docker info &>/dev/null; then
    error "Docker daemon is not running. Start Docker Desktop."
    ok=false
  else
    success "Docker daemon is running"
  fi

  if ! docker compose version &>/dev/null; then
    error "Docker Compose v2 not found. Update Docker Desktop."
    ok=false
  else
    success "Docker Compose found: $(docker compose version --short)"
  fi

  if [[ "$ok" == "false" ]]; then
    echo ""
    error "Prerequisites check failed. Fix the issues above and retry."
    exit 1
  fi

  # Detect Apple Silicon
  if [[ "$(uname -m)" == "arm64" ]]; then
    warn "Apple Silicon detected (arm64). Docker images will build for linux/arm64."
    warn "To build amd64 images for deployment, use GitHub Actions (buildx multi-arch)."
  fi
}

# ─── Environment file ─────────────────────────────────────────────────────────
write_env_file() {
  local env_file="deploy/.env"

  # Resolve feed settings — mock mode overrides everything
  local feed_flight ship_feed satellites_enabled spring_profiles
  local mock_seed mock_flights mock_ships mock_satellites

  if [[ "${MOCK_MODE:-false}" == "true" ]]; then
    feed_flight="mock"
    ship_feed="mock"
    satellites_enabled="false"
    spring_profiles="mock"
  else
    feed_flight="${INGESTION_FEED_FLIGHT:-mock}"
    ship_feed="${INGESTION_FEED_SHIP:-mock}"
    satellites_enabled="${SATELLITES_ENABLED:-false}"
    spring_profiles="${SPRING_PROFILES_ACTIVE:-}"
  fi

  mock_seed="${MOCK_SEED:-42}"
  mock_flights="${MOCK_FLIGHTS_COUNT:-500}"
  mock_ships="${MOCK_SHIPS_COUNT:-200}"
  mock_satellites="${MOCK_SATELLITES_COUNT:-100}"

  cat > "$env_file" <<EOF
# Auto-generated by run.sh — do not commit
AISSTREAM_API_KEY=${AISSTREAM_API_KEY:-}
OPENSKY_USERNAME=${OPENSKY_USERNAME:-}
OPENSKY_PASSWORD=${OPENSKY_PASSWORD:-}
GATEWAY_API_KEY=${GATEWAY_API_KEY:-dev-key}
INGESTION_FEED_FLIGHT=${feed_flight}
INGESTION_FEED_SHIP=${ship_feed}
SATELLITES_ENABLED=${satellites_enabled}
SPRING_PROFILES_ACTIVE=${spring_profiles}
MOCK_SEED=${mock_seed}
MOCK_FLIGHTS_COUNT=${mock_flights}
MOCK_SHIPS_COUNT=${mock_ships}
MOCK_SATELLITES_COUNT=${mock_satellites}
EOF
  info "Environment written to $env_file"

  # ── Report what's running ───────────────────────────────────
  if [[ "${MOCK_MODE:-false}" == "true" ]]; then
    success "Mode: mock (deterministic, no internet required)"
    info "  Flights:    ${mock_flights} aircraft (seed ${mock_seed})"
    info "  Ships:      ${mock_ships} vessels (seed ${mock_seed})"
    info "  Satellites: ${mock_satellites} mock satellites"
    return
  fi

  if [[ "${feed_flight}" == "opensky" ]]; then
    success "Flight data: OpenSky Network (real ADS-B)"
    if [[ -n "${OPENSKY_USERNAME:-}" ]]; then
      info "  OpenSky: authenticated as ${OPENSKY_USERNAME}"
    else
      warn "  OpenSky: anonymous mode (10 req/min) — register for higher limits"
    fi
  elif [[ "${feed_flight}" == "adsb" ]]; then
    success "Flight data: ADSBExchange (real ADS-B)"
  else
    info "Flight data: mock simulator (${mock_flights} aircraft)"
  fi

  if [[ "${ship_feed}" == "aisstream" ]]; then
    if [[ -z "${AISSTREAM_API_KEY:-}" ]]; then
      error "AISSTREAM_API_KEY is required when INGESTION_FEED_SHIP=aisstream"
      error "Get a free key at: https://aisstream.io"
      exit 1
    fi
    success "Ship data: AISStream.io (real AIS)"
  elif [[ "${ship_feed}" == "aishub" ]]; then
    success "Ship data: AISHub (real AIS)"
  else
    info "Ship data: mock simulator (${mock_ships} vessels)"
  fi

  if [[ "${satellites_enabled}" == "true" ]]; then
    success "Satellites: Celestrak TLE feed (real)"
  else
    info "Satellites: mock simulator (${mock_satellites} satellites)"
  fi
}

# ─── Build ────────────────────────────────────────────────────────────────────
build_images() {
  header "Building Docker images..."
  info "This may take several minutes on first build (JDK + npm downloads)."
  docker compose -f "$COMPOSE_FILE" build --parallel
  success "All images built"
}

# ─── Up ───────────────────────────────────────────────────────────────────────
start_services() {
  header "Starting services..."
  docker compose -f "$COMPOSE_FILE" up -d

  echo ""
  header "Waiting for services to be healthy..."
  local max_wait=120
  local elapsed=0

  while [[ $elapsed -lt $max_wait ]]; do
    local healthy
    healthy=$(docker compose -f "$COMPOSE_FILE" ps --format json 2>/dev/null | \
              python3 -c "import sys,json; data=sys.stdin.read();
items=[json.loads(l) for l in data.strip().split('\n') if l.strip()];
print(sum(1 for i in items if i.get('Health','') in ('healthy','') and i.get('State','')=='running'))" 2>/dev/null || echo "0")
    local total
    total=$(docker compose -f "$COMPOSE_FILE" ps -q 2>/dev/null | wc -l | tr -d ' ')

    if [[ "$healthy" == "$total" && "$total" -gt 0 ]]; then
      break
    fi

    printf "\r  Waiting... %ds / %ds (containers up: %s/%s)" "$elapsed" "$max_wait" "$healthy" "$total"
    sleep 5
    elapsed=$((elapsed + 5))
  done
  echo ""

  echo ""
  show_status

  echo ""
  success "Digital Twin Earth is running!"
  echo ""
  echo -e "  ${BOLD}Frontend:${RESET}  http://localhost:4200"
  echo -e "  ${BOLD}API:${RESET}       http://localhost:8080/api/flights"
  echo -e "  ${BOLD}Health:${RESET}    http://localhost:8080/actuator/health"
  echo ""
  echo -e "  To stream live data:"
  echo -e "  ${BLUE}curl -H 'X-Api-Key: dev-key' http://localhost:8080/api/stream/flights${RESET}"
  echo ""
  echo -e "  Follow logs: ${BLUE}./run.sh logs${RESET}"
  echo -e "  Stop:        ${BLUE}./run.sh down${RESET}"
}

# ─── Down ─────────────────────────────────────────────────────────────────────
stop_services() {
  header "Stopping services..."
  docker compose -f "$COMPOSE_FILE" down
  success "All services stopped"
}

# ─── Status ───────────────────────────────────────────────────────────────────
show_status() {
  docker compose -f "$COMPOSE_FILE" ps
}

# ─── Logs ─────────────────────────────────────────────────────────────────────
follow_logs() {
  docker compose -f "$COMPOSE_FILE" logs -f --tail=100
}

# ─── Clean ────────────────────────────────────────────────────────────────────
clean() {
  warn "This will REMOVE all containers, networks, and volumes (database data)!"
  read -rp "Are you sure? (y/N) " confirm
  if [[ "$confirm" =~ ^[Yy]$ ]]; then
    docker compose -f "$COMPOSE_FILE" down -v --remove-orphans
    success "Cleaned up"
  else
    info "Cancelled"
  fi
}

# ─── Main ─────────────────────────────────────────────────────────────────────
main() {
  echo -e "${BOLD}Digital Twin Earth — Local Runner${RESET}"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  # Parse optional mode prefix: `run.sh mock <cmd>` or `run.sh <cmd>`
  local arg1="${1:-up}"
  local cmd

  if [[ "$arg1" == "mock" ]]; then
    export MOCK_MODE=true
    cmd="${2:-up}"
    info "Mock mode enabled"
  else
    export MOCK_MODE=false
    cmd="$arg1"
  fi

  case "$cmd" in
    up)
      check_prereqs
      write_env_file
      build_images
      start_services
      ;;
    down)
      stop_services
      ;;
    restart)
      stop_services
      check_prereqs
      write_env_file
      start_services
      ;;
    build)
      check_prereqs
      write_env_file
      build_images
      ;;
    logs)
      follow_logs
      ;;
    status)
      show_status
      ;;
    clean)
      clean
      ;;
    help|--help|-h)
      usage
      ;;
    *)
      error "Unknown command: $cmd"
      usage
      exit 1
      ;;
  esac
}

main "$@"
